//
// ChannelsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

open class ChannelsAPI {
    /**
     Get list of Channels

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAllChannels(apiResponseQueue: DispatchQueue = DemoTvGuideSwaggerApiAPI.apiResponseQueue, completion: @escaping ((_ data: [Channel]?, _ error: Error?) -> Void)) -> RequestTask {
        getAllChannelsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get list of Channels
     - GET /Channels
     - returns: RequestBuilder<[Channel]>
     */
    open class func getAllChannelsWithRequestBuilder() -> RequestBuilder<[Channel]> {
        let localVariablePath = "/Channels"
        let localVariableURLString = DemoTvGuideSwaggerApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [:]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Channel]>.Type = DemoTvGuideSwaggerApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: localVariableUrlComponents?.string ?? localVariableURLString, parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
