//
// ProgramItemsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

open class ProgramItemsAPI {
    /**
     Get list of ProgramItems

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getProgramItems(apiResponseQueue: DispatchQueue = DemoTvGuideSwaggerApiAPI.apiResponseQueue, completion: @escaping ((_ data: [ProgramItem]?, _ error: Error?) -> Void)) -> RequestTask {
        getProgramItemsWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get list of ProgramItems
     - GET /ProgramItems
     - returns: RequestBuilder<[ProgramItem]>
     */
    open class func getProgramItemsWithRequestBuilder() -> RequestBuilder<[ProgramItem]> {
        let localVariablePath = "/ProgramItems"
        let localVariableURLString = DemoTvGuideSwaggerApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [:]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ProgramItem]>.Type = DemoTvGuideSwaggerApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: localVariableUrlComponents?.string ?? localVariableURLString, parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
