//
// ProgramItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Class describes Program Guide item */
public struct ProgramItem: Codable, JSONEncodable, Hashable {
    public var startTime: Date
    public var recentAirTime: RecentAirTime
    public var length: Int64
    public var name: String

    public init(startTime: Date, recentAirTime: RecentAirTime, length: Int64, name: String) {
        self.startTime = startTime
        self.recentAirTime = recentAirTime
        self.length = length
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startTime
        case recentAirTime
        case length
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(recentAirTime, forKey: .recentAirTime)
        try container.encode(length, forKey: .length)
        try container.encode(name, forKey: .name)
    }
}
