//
// RecentAirTime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/** Class to join programs and channels */
public struct RecentAirTime: Codable, JSONEncodable, Hashable {
    public var id: Int64
    public var channelID: Int64

    public init(id: Int64, channelID: Int64) {
        self.id = id
        self.channelID = channelID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case channelID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(channelID, forKey: .channelID)
    }
}
